language: go
go:
 - "1.x"
 - "1.12.x"
 - master

env:
 global: 
 - GO111MODULE=on
 
 script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -v -race ./...  # Run all the tests with the race detector enabled
